# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Shared Blackball - Build Solution File

on:
 workflow_call:
    inputs:
     solution_file_name:
      required: true
      type: string
jobs:
  # The 'build' name is important and referenced in blackball_net_publish_project
  build: 
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
        
      - name: Initialize Blackball Nuget Farm
        run: dotnet nuget add source --name blackball "https://nuget.blackballsoftware.com/api/v2"
        
      - name: Install dependencies
        run: dotnet restore "${{ inputs.solution_file_name }}"
        
      - name: Build dependencies
        run: dotnet build "${{ inputs.solution_file_name }}" --no-restore -c Release
        
