# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Shared Blackball - Publish to Azure

on:
 workflow_call:
    inputs:
     project_to_deploy:
      required: true
      type: string
     azure_app_name:
      required: true
      type: string
     working_directory:
      required: false
      type: string
      default: ./
    secrets:
      azure_publish_profile:
        required: true

jobs:

  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Bump version
        shell: pwsh
        run: |
            Get-Date -Format "3.yy.MMdd.HHmm" | Set packageVersion
            
            "Bumping calculated version $packageVersion"
            Set versionTag "<FileVersion>$packageVersion</FileVersion>"
            Get-ChildItem -Path .\ -Filter *.csproj -Recurse -File -Name| ForEach-Object {
                Set csprojFilePath $_
                "Patching $csprojFilePath"
                ((Get-Content -path $csprojFilePath -Raw) -replace '\<FileVersion\>[^\<]+\</FileVersion\>', $versionTag) | Set-Content -path $csprojFilePath
            }
            
            "Bumping service worker version $packageVersion"
            Set swTag "const VERSION = ""$packageVersion"";"
            Get-ChildItem -Path .\ -Filter serviceworker.* -Recurse -File -Name| ForEach-Object {
             Set swFilePath $_
             "Patching $swFilePath"
             ((Get-Content -path $swFilePath -Raw) -replace 'const VERSION = \"[^\"]+\";', $swTag) | Set formattedFile
             Set-Content $formattedFile -path $swFilePath
            }

